apiVersion: v1
kind: Service
metadata:
  name: next-app-service
spec:
  type: LoadBalancer
  selector:
    app: next-app
  ports:
    - name: http
      port: 3000 # service port
      targetPort: 3000 # target ( container ) port
